spring.application.name=mobilebroker
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_broker_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

# SMSPoh
smspoh.api.baseUrl=https://v3.smspoh.com/api/rest/send
smspoh.api.authToken=V2ZoaGV6V05YUzB2aGZ6d3o0bEJNMlZaelA3M01jWl86SUxmRzVsaEZUQ3dSZ3pzUzloSHlEQjA2blVYNUgyS0M=
smspoh.api.name=SMSPoh

# Infobip
infobip.api.baseUrl=https://jl61n.api.infobip.com/sms/2/text/single
infobip.api.encodedAuth=bW1idXN0aWNrZXQ6bW1CLTAwOTAwJSU=
infobip.api.name=Infobip