spring.application.name=mobilebroker
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_broker_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

smspoh.auth.token=V2ZoaGV6V05YUzB2aGZ6d3o0bEJNMlZaelA3M01jWl86SUxmRzVsaEZUQ3dSZ3pzUzloSHlEQjA2blVYNUgyS0M=
smspoh.api.url=https://v3.smspoh.com/api/rest/send
smspoh.provider.name=Infobip